"use strict";
require("angular2-google-maps/core");
require("ng2-bootstrap");
require("ng2-dropdown");
require("moment");
require("rxjs/RX");
require("angular-in-memory-web-api");
//import 'jaydata/core';
//import 'jaydata/odata';
require("ag-grid-ng2/main");
require("ag-grid/main");
require("ng2-cloudinary");
require("ng2-file-upload");
require("ng2-auto-complete");
require("ng2-datepicker");
require("ng2-datetime");
require("ng2-slimscroll");
require("underscore");
require("ng2-modal");
require("angular-google-signin");
require("angular2-jwt");
require("core-js-shim");
require("zone");
require("reflect-metadata");
//# sourceMappingURL=vendor.js.map