
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MSNServiceApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Client
{

    public int id { get; set; }

    public string key { get; set; }

    public string Secret { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> ApplicationType { get; set; }

    public Nullable<bool> Active { get; set; }

    public string AllowedOrigin { get; set; }

    public Nullable<decimal> RefreshTokenLifeTime { get; set; }

    public Nullable<decimal> CITYAREAID { get; set; }

    public Nullable<int> LOGINTYPEID { get; set; }

    public string CURRENTLOCATION { get; set; }

    public Nullable<double> USERLOCATIONLATITUDE { get; set; }

    public Nullable<double> USERLOCATIONLONGITUDE { get; set; }



    public virtual CITYAREA CITYAREA { get; set; }

    public virtual SOCIALLOGIN SOCIALLOGIN { get; set; }

}

}
