//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSNServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICEBID
    {
        public SERVICEBID()
        {
            this.SERVICEBIDNEEDFILES = new HashSet<SERVICEBIDNEEDFILE>();
            this.USERSERVICENEEDs = new HashSet<USERSERVICENEED>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> USERSERVICENEEDID { get; set; }
        public string BIDTITLE { get; set; }
        public string BIDDESCRIPTION { get; set; }
        public Nullable<decimal> BIDAMOUNT { get; set; }
    
        public virtual ICollection<SERVICEBIDNEEDFILE> SERVICEBIDNEEDFILES { get; set; }
        public virtual USERINFO USERINFO { get; set; }
        public virtual USERSERVICENEED USERSERVICENEED { get; set; }
        public virtual ICollection<USERSERVICENEED> USERSERVICENEEDs { get; set; }
    }
}
