
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MSNServiceApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class USERSERVICETIMERECORD
{

    public USERSERVICETIMERECORD()
    {

        this.USERSERVICENEEDs = new HashSet<USERSERVICENEED>();

    }


    public decimal ID { get; set; }

    public Nullable<System.DateTime> SERVICEBOOKEDDATE { get; set; }

    public Nullable<System.DateTime> SERVICESTARTDATE { get; set; }

    public Nullable<System.DateTime> SERVICEENDDATE { get; set; }

    public Nullable<System.TimeSpan> SERVICESTARTTIME { get; set; }

    public Nullable<System.TimeSpan> SERVICEENDTIME { get; set; }



    public virtual ICollection<USERSERVICENEED> USERSERVICENEEDs { get; set; }

}

}
