//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSNServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERSERVICE()
        {
            this.USERSERVICEFILES = new HashSet<USERSERVICEFILE>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> SERVICECATEGORYID { get; set; }
        public Nullable<decimal> SERVICESUBCATEGORYID { get; set; }
    
        public virtual SERVICECATEGORY SERVICECATEGORY { get; set; }
        public virtual SERVICESUBCATEGORY SERVICESUBCATEGORY { get; set; }
        public virtual USERINFO USERINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSERVICEFILE> USERSERVICEFILES { get; set; }
    }
}
