//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSNServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSERVICENEED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERSERVICENEED()
        {
            this.SERVICEBIDs = new HashSet<SERVICEBID>();
            this.USERSERVICETIMEREOCRDs = new HashSet<USERSERVICETIMEREOCRD>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string SERVICELOCATION { get; set; }
        public string SERVICETITLE { get; set; }
        public string SERVICEDESCRIPTION { get; set; }
        public Nullable<decimal> SERVICECATEGORYID { get; set; }
        public Nullable<decimal> SERVICESUBCATEGORYID { get; set; }
        public Nullable<decimal> MINBUDGET { get; set; }
        public Nullable<decimal> MAXBUDGET { get; set; }
        public Nullable<int> SERVICESTATE { get; set; }
        public Nullable<int> SERVICETIMETYPE { get; set; }
        public Nullable<decimal> ALLOCATEDBIDID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEBID> SERVICEBIDs { get; set; }
        public virtual SERVICEBID SERVICEBID { get; set; }
        public virtual SERVICECATEGORY SERVICECATEGORY { get; set; }
        public virtual SERVICESTATE SERVICESTATE1 { get; set; }
        public virtual SERVICESUBCATEGORY SERVICESUBCATEGORY { get; set; }
        public virtual SERVICETIMETYPE SERVICETIMETYPE1 { get; set; }
        public virtual USERINFO USERINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSERVICETIMEREOCRD> USERSERVICETIMEREOCRDs { get; set; }
    }
}
