//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSNServiceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERMEMBERSHIP
    {
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> MEMBERSHIPID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual MEMBERSHIP MEMBERSHIP { get; set; }
        public virtual USERINFO USERINFO { get; set; }
    }
}
